// Auto-generated by scripts/generate_icons.ts
import { type Icon } from "@phosphor-icons/react";
import { GithubLogoIcon } from "@phosphor-icons/react/dist/csr/GithubLogo";

export const SocialIcons: Record<string, Icon> = {
  "github": GithubLogoIcon,
};
