import { getConfig } from "../utils.ts";

const ICON_DIR = "./node_modules/@phosphor-icons/react/dist/csr";

async function getAvailableIcons(): Promise<Set<string>> {
  const icons = new Set<string>();
  try {
    for await (const entry of Deno.readDir(ICON_DIR)) {
      if (entry.isFile && entry.name.endsWith(".d.ts")) {
        icons.add(entry.name.replace(".d.ts", ""));
      }
    }
  } catch (_e) {
    // console.warn("Could not read icon directory, falling back to heuristics:", e);
  }
  return icons;
}

async function main() {
  console.log("Generating social icons...");
  const config = await getConfig();

  if (!config.social || config.social.length === 0) {
    console.log("No social icons found in config.toml");
    // Create an empty file or default to avoid errors
    await Deno.writeTextFile(
      "components/SocialIcons.tsx",
      `// Auto-generated
import { type Icon } from "@phosphor-icons/react";
export const SocialIcons: Record<string, Icon> = {};
`,
    );
    return;
  }

  const availableIcons = await getAvailableIcons();
  const imports: string[] = [];
  const mapEntries: string[] = [];
  const processedIcons = new Set<string>();

  for (const item of config.social) {
    const rawIcon = item.icon;
    if (processedIcons.has(rawIcon)) continue;
    processedIcons.add(rawIcon);

    const pascalName = rawIcon.charAt(0).toUpperCase() + rawIcon.slice(1);
    let componentName = pascalName;

    // Try to find exact match or Logo match
    if (availableIcons.size > 0) {
      if (availableIcons.has(pascalName + "Logo")) {
        componentName = pascalName + "Logo";
      } else if (availableIcons.has(pascalName)) {
        componentName = pascalName;
      } else {
        console.warn(
          `Warning: Could not find icon for "${rawIcon}". Defaulting to "${pascalName}".`,
        );
      }
    } else {
      // Fallback if we can't read directory
      if (
        [
          "Github",
          "Twitter",
          "Linkedin",
          "Facebook",
          "Instagram",
          "Youtube",
          "Twitch",
          "Discord",
          "Medium",
          "Reddit",
          "Tiktok",
          "Whatsapp",
          "Telegram",
          "Slack",
          "Spotify",
        ].includes(pascalName)
      ) {
        componentName = pascalName + "LogoIcon";
      }
    }

    imports.push(
      `import { ${componentName}Icon } from "@phosphor-icons/react/dist/csr/${componentName}";`,
    );
    mapEntries.push(`  "${rawIcon}": ${componentName}Icon,`);
  }

  const content = `// Auto-generated by scripts/generate_icons.ts
import { type Icon } from "@phosphor-icons/react";
${imports.join("\n")}

export const SocialIcons: Record<string, Icon> = {
${mapEntries.join("\n")}
};
`;

  await Deno.writeTextFile("components/SocialIcons.tsx", content);
  console.log("Generated components/SocialIcons.tsx");
}

if (import.meta.main) {
  await main();
}
